
package com.ensoa.orderservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderSerivceEndpoint", targetNamespace = "http://orderservice.ensoa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderSerivceEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ensoa.orderservice.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.GetOrderResponse")
    @Action(input = "http://orderservice.ensoa.com/OrderSerivceEndpoint/getOrderRequest", output = "http://orderservice.ensoa.com/OrderSerivceEndpoint/getOrderResponse")
    public Order getOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "purchaseOrder", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.PurchaseOrder")
    @ResponseWrapper(localName = "purchaseOrderResponse", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.PurchaseOrderResponse")
    @Action(input = "http://orderservice.ensoa.com/OrderSerivceEndpoint/purchaseOrderRequest", output = "http://orderservice.ensoa.com/OrderSerivceEndpoint/purchaseOrderResponse")
    public void purchaseOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ensoa.orderservice.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://orderservice.ensoa.com/", className = "com.ensoa.orderservice.GetOrdersResponse")
    @Action(input = "http://orderservice.ensoa.com/OrderSerivceEndpoint/getOrdersRequest", output = "http://orderservice.ensoa.com/OrderSerivceEndpoint/getOrdersResponse")
    public List<Order> getOrders(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

}
